apiVersion: v1
kind: Pod
metadata:
  name: "mypod5"
  labels:
    dc: IN
    team: team1

spec:
  containers:
  - name: "mycdb"
    image: "mysql"
    env:
      # Use secret in real usage
    - name: MYSQL_ROOT_PASSWORD
      value: password