apiVersion: v1
kind: Pod
metadata:
  name: "mypod4"
  labels:
    dc: IN
    team: team1

spec:
  containers:
  - name: "myc1"
    image: "vimal13/apache-webserver-php"
    env: 
    - name: x
      value: "Heyy, Malhar"