apiVersion: v1
kind: Pod
metadata:
  name: "mypod6"
  labels:
    region: IN

spec:
  volumes: 
  - name: s1
    persistentVolumeClaim:
       claimName: malharpvc
    
  containers:
  - name: "myc2"
    image: "vimal13/apache-webserver-php"
    volumeMounts:
     - mountPath: "/var/www/data"
       name: s1