apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
    matchExpressions:
    - { key: dc, operator: In, values: [ south ] } #Don't confuse. coz, dc is not value it is key and south is value.
    - { key: region, operator: In, values: [ IN ] }

  template:
    metadata:
      name: "mypod6"
      labels:
        region: IN
        dc : south
        app: web 

    spec:
      containers:
      - name: "myc1"
        image: "vimal13/apache-webserver-php"
        env: 
        - name: x
          value: "Heyy, Malhar"


